export const parks = [
  {
    id: 1,
    name: "Hirkan National Park",
    lat: 38.45,
    lng: 48.87,
    region: "Lankaran",
  },
  {
    id: 2,
    name: "Shirvan National Park",
    lat: 39.95,
    lng: 49.22,
    region: "Salyan",
  },
  {
    id: 3,
    name: "Absheron National Park",
    lat: 40.34,
    lng: 50.11,
    region: "Absheron",
  },
  {
    id: 4,
    name: "Shamakhi National Park",
    lat: 40.63,
    lng: 48.65,
    region: "Shamakhi",
  },
  { id: 5, name: "Ilisu National Park", lat: 41.5, lng: 46.02, region: "Gakh" },
  {
    id: 6,
    name: "Zangezur National Park",
    lat: 39.2,
    lng: 46.55,
    region: "Ordubad",
  },
  {
    id: 7,
    name: "Ordubad National Park",
    lat: 38.9,
    lng: 45.98,
    region: "Ordubad",
  },
  {
    id: 8,
    name: "Şahdağ National Park",
    lat: 41.28,
    lng: 47.9,
    region: "Guba",
  },
  {
    id: 9,
    name: "Göygöl National Park",
    lat: 40.59,
    lng: 46.35,
    region: "Goygol",
  },
  {
    id: 10,
    name: "Korchay National Park",
    lat: 40.75,
    lng: 47.12,
    region: "Gabala",
  },
  {
    id: 11,
    name: "Aladaghlar National Park",
    lat: 40.22,
    lng: 47.65,
    region: "Goranboy",
  },
  {
    id: 12,
    name: "Axar-Bakhar National Park",
    lat: 41.55,
    lng: 46.3,
    region: "Gakh",
  },
];
